<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '177697eb0a3415d718fec5c25c5bdbac',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/vetcloud?serverVersion=8&charset=utf8mb4',
  'ASSETS_VERSION' => '1.0.0',
  'JWT_SECRET' => 'm@ddy@43!@%$!@',
  'JWT_ISSUER' => 'kennethmarco',
  'JWT_AUD' => 'dev.vetcloud.com',
  'JWT_ALGO' => 'HS512',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '7f38ec3be6cfabfdac00e1f0b471ee68',
  'WKHTMLTOPDF_PATH' => 'C:/projects/vetcloud_new/wkhtmltopdf/bin/wkhtmltopdf',
  'WKHTMLTOIMAGE_PATH' => 'C:/projects/vetcloud_new/wkhtmltopdf/bin/wkhtmltoimage',
);
