<?php

namespace App\Repository;

use App\Entity\BillingEntity;

/**
 * BillingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingRepository extends \Doctrine\ORM\EntityRepository
{

    public function validate($billing_form) {

     
    }

    public function ajax_list(array $get, $userData){

        $columns = array(
            array('a.`id`', "a.`id`", "admissionId"),
            array("CONCAT(c.`first_name`, ' ', c.`last_name`)", "CONCAT(c.`first_name`, ' ', c.`last_name`)", 'client'),
            array('b.`status`', "b.`status`", "status"),
            array('b.`amount_due`', "b.`amount_due`", "totalAmountDue"),
            array('(b.amount_due - IFNULL(p.payment, 0))', '(b.amount_due - IFNULL(p.payment, 0))', "amountDue"),
            array('IFNULL(p.payment, 0)', "IFNULL(p.payment, 0)", "payment"),
            array('DATE_FORMAT(b.`created_at`, "%m/%d/%Y")', 'DATE_FORMAT(b.`created_at`, "%m/%d/%Y")', 'billingDate'),
            array('b.`id`', "b.`id`", "id"),
        );
        $asColumns = array();

        $select = "SELECT";
        $from = "FROM `billing` b";
        $sqlWhere = " WHERE a.`is_deleted` = 0";
        $joins = " LEFT JOIN `admission` a ON a.`id` = b.`admission_id`";
        $joins .= " LEFT JOIN `client` c ON c.`id` = a.`client_id`";
        $joins .= " LEFT JOIN (
                        SELECT
                            SUM(p.`amount`) AS payment,
                            p.`billing_id`
                        FROM `payment` p
                        GROUP BY p.`billing_id`
                ) p ON p.`billing_id` = b.`id`";

        $groupBy = "";
        $orderBy = "";
        $limit = "";
        $stmtParams = array();

        foreach($columns as $key => $column) {
            $select .= ($key > 0 ? ', ' : ' ') . $column[1] . (isset($column[2]) ? ' AS ' . $column[2] : '');
        }


        if($userData['type'] != 'Super Admin' || $userData['branchId']){

            $sqlWhere .= " AND c.`branch_id` = :branchId";
            $stmtParams['branchId'] = $userData['branchId'];
        }

        /*
         * Ordering
         */
        foreach($get['columns'] as $key => $column) {
            if($column['orderable']=='true') {
                if(isSet($get['order'])) {
                    foreach($get['order'] as $order) {
                        if($order['column']==$key) {
                            $orderBy .= (!empty($orderBy) ? ', ' : 'ORDER BY ') . $columns[$key][0] . (!empty($order['dir']) ? ' ' . $order['dir'] : '');
                        }
                    }
                }
            }
        }

        /*
         * Filtering
         */
        if(isset($get['search']) && $get['search']['value'] != ''){
            $aLikes = array();
            foreach($get['columns'] as $key => $column) {
                if($column['searchable']=='true') {
                    $aLikes[] = $columns[$key][0] . ' LIKE :searchValue';
                }
            }
            foreach($asColumns as $asColumn) {
                $aLikes[] = $asColumn . ' LIKE :searchValue';
            }
            if(count($aLikes)) {
                $sqlWhere .= (!empty($sqlWhere) ? ' AND ' : 'WHERE ') . '(' . implode(' OR ', $aLikes) . ')';
                $stmtParams['searchValue'] = "%" . $get['search']['value'] . "%";
            }
        }

        /* Set Limit and Length */
        if(isset( $get['start'] ) && $get['length'] != '-1'){
            $limit = 'LIMIT ' . (int)$get['start'] . ',' . (int)$get['length'];
        }

        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
     

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result_count = $res->fetchAllAssociative();
        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy $limit";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();

        /* Data Count */
        $recordsTotal = count($result_count);

        /*
         * Output
         */
        $output = array(
            "draw" => intval($get['draw']),
            "recordsTotal" => $recordsTotal,
            "recordsFiltered" => $recordsTotal,
            "data" => array()
        );

        $url = $get['url'];
        $formUrl = '';
        $hasDetails = false;
        if($userData['type'] == 'Super Admin'  || in_array('Billing Details', $userData['accesses'])){

            $formUrl = $url . 'billing/details';  
            $hasDetails = true;
        }

        foreach($result as $row) {

            $id = base64_encode($row['id']);
        
            $action = $hasDetails ? "<a class='action-button-style btn btn-primary table-btn' href='$formUrl/$id'>Update</a>" : "";

            $values = array(
                $row['admissionId'],
                $row['client'],
                $row['status'],
                $row['totalAmountDue'],
                $row['amountDue'],
                $row['payment'],
                $row['billingDate'],
                $action,
            );

            $output['data'][] = $values;
        }

        unset($result);

        return $output;
    }

    public function payment_ajax_list(array $get, $userData){

        $columns = array(
            array('DATE_FORMAT(p.`createdat`, "%m/%d/%Y")', 'DATE_FORMAT(p.`createdat`, "%m/%d/%Y")', "paymentDate"),
            array('pt.`description`', "pt.`description`", "paymentType"),
            array('p.`amount_due`', "p.`amount`", "amount"),
            array('p.`id`', "p.`id`", "id"),
        );
        $asColumns = array();

        $select = "SELECT";
        $from = "FROM `payment` p";
        $sqlWhere = " WHERE p.`is_deleted` = 0";
        $sqlWhere .= " AND p.`billing_id` =:billingId";
        $joins = " LEFT JOIN `payment_type` pt ON pt.`id` = p.`payment_type_id`";
        $groupBy = "";
        $orderBy = "";
        $limit = "";
        $stmtParams = array();


        $stmtParams['billingId'] = $get['billingId'];
        

        foreach($columns as $key => $column) {
            $select .= ($key > 0 ? ', ' : ' ') . $column[1] . (isset($column[2]) ? ' AS ' . $column[2] : '');
        }


        if($userData['type'] != 'Super Admin' || $userData['branchId']){

            $sqlWhere .= " AND c.`branch_id` = :branchId";
            $stmtParams['branchId'] = $userData['branchId'];
        }

        /*
         * Ordering
         */
        foreach($get['columns'] as $key => $column) {
            if($column['orderable']=='true') {
                if(isSet($get['order'])) {
                    foreach($get['order'] as $order) {
                        if($order['column']==$key) {
                            $orderBy .= (!empty($orderBy) ? ', ' : 'ORDER BY ') . $columns[$key][0] . (!empty($order['dir']) ? ' ' . $order['dir'] : '');
                        }
                    }
                }
            }
        }

        /*
         * Filtering
         */
        if(isset($get['search']) && $get['search']['value'] != ''){
            $aLikes = array();
            foreach($get['columns'] as $key => $column) {
                if($column['searchable']=='true') {
                    $aLikes[] = $columns[$key][0] . ' LIKE :searchValue';
                }
            }
            foreach($asColumns as $asColumn) {
                $aLikes[] = $asColumn . ' LIKE :searchValue';
            }
            if(count($aLikes)) {
                $sqlWhere .= (!empty($sqlWhere) ? ' AND ' : 'WHERE ') . '(' . implode(' OR ', $aLikes) . ')';
                $stmtParams['searchValue'] = "%" . $get['search']['value'] . "%";
            }
        }

        /* Set Limit and Length */
        if(isset( $get['start'] ) && $get['length'] != '-1'){
            $limit = 'LIMIT ' . (int)$get['start'] . ',' . (int)$get['length'];
        }

        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
     

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result_count = $res->fetchAllAssociative();
        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy $limit";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();

        /* Data Count */
        $recordsTotal = count($result_count);

        /*
         * Output
         */
        $output = array(
            "draw" => intval($get['draw']),
            "recordsTotal" => $recordsTotal,
            "recordsFiltered" => $recordsTotal,
            "data" => array()
        );

        $url = $get['url'];
        $formUrl = '';
        $hasDetails = false;
        if($userData['type'] == 'Super Admin'  || in_array('Billing Details Payment Update', $userData['accesses'])){

            $formUrl = $url . 'billing/' . $get['billingId'] . '/payment/form/u/';  
            $hasDetails = true;
        }

        foreach($result as $row) {

            $id = base64_encode($row['id']);
        
            $action = $hasDetails ? "<a class='action-button-style btn btn-primary table-btn' href='$formUrl/$id'>Update</a>" : "";

            $values = array(
                $row['paymentDate'],
                $row['paymentType'],
                number_format($row['amount'], 2, ".", ","),
                $action,
            );

            $output['data'][] = $values;
        }

        unset($result);

        return $output;
    }


}
